export const QUESTION_LIST = {
	general_Q1: "Do you need to stand or walk for major part of your day?",
	general_Q2: "Are you recreational or professional  athlete?",
	general_Q3: "Are you Diabetic?",
	general_Q4: "Do you have corn/ callus?",
	general_Q5: "Do you have any Foot Deformity?",
	general_Q6: "Do you have Foot Pain?",
	general_Q7: "Is the pain aggravated walking barefoot?",
	general_Q8: "Does the pain feel like Sharp burning pain?",
	general_Q9: "Do you feel like there is a pebble when you stand or walk?",
	general_Q10: "Is the pain aggravated on prolonged standing and walking?",
	general_Q11: "Do you experience calf muscle pain at the end of the day?",
	general_Q12: "Is there less pain in the morning after a good night sleep?",
	general_Q13: "Is it painful if you press on the area that you pointed out?",
	general_Q14: "Is there any swelling over the area?",
	general_Q15: "Does it hurt when you take the first step in the morning?",
	general_Q16: "After you take a few steps after prolonged sitting?",
	general_Q17: "Is there any swelling over your heel?",
	general_Q18: "Does it hurt if you press on the swelling?",
	general_Q19: "Is it painful to move your ankle up and down?",
	general_Q20: "Is there any swelling around your big toe?",
	general_Q21: "Do you have any one of your toes riding up or pushing out an adjacent toe ? (Crossover toe)",
	general_Q22: "Is the pain aggravated on walking fast or running?",
	general_Q23: "Is it painful if you try to move your big toe?",
	general_Q24: "Is the pain maximum the undersurface of your big toe?",
	general_Q25: "Do you have a twisting injury in the past few days?",
	general_Q26: "Is there any ankle swelling?",
	general_Q27: "Past few weeks/ Month?",
	general_Q28: "Is there any ankle swelling?",
	general_Q29: "Do you feel your ankle is unstable (i,e) you get frequent ankle sprain?",
	general_Q30: "Is the pain aggravated by walking?",
	general_Q31: "Do you feel your pain is deep inside your ankle?",
	general_Q32: "Have been recent injury?",
	general_Q33: "Is the pain there more than two weeks?",
	general_Q34: "Is the pain aggravated by walking/ running?",
	general_Q35: "Does it hurt if someone presses hard over the area?",
	general_Q36: "Is there any local swelling over that part of the foot?",
	general_Q37: "Is there any history of a previous injury which required treatment?"
};